# Generated by Django 2.2.1 on 2019-06-03 15:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph')), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('description', wagtail.core.blocks.CharBlock(help_text='Used as ALT text', required=False)), ('caption', wagtail.core.blocks.CharBlock(help_text='Shown below the image', required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('new_window', wagtail.core.blocks.BooleanBlock(label='Open link in new window', required=False))])), ('html', wagtail.core.blocks.RawHTMLBlock(label='HTML'))], blank=True)),
                ('share_description', models.TextField(blank=True, help_text="\n        Default message shown when a page from this site is shared on social media. This message can be\n        changed per page, under the 'promote' tab.\n        ", max_length=150)),
                ('share_image', models.ForeignKey(blank=True, help_text="\n        Default image shown when a page from this site is shared on social media. This image can be\n        changed per page, under the 'promote' tab.\n        ", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(icon='fa-paragraph')), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('description', wagtail.core.blocks.CharBlock(help_text='Used as ALT text', required=False)), ('caption', wagtail.core.blocks.CharBlock(help_text='Shown below the image', required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('new_window', wagtail.core.blocks.BooleanBlock(label='Open link in new window', required=False))])), ('html', wagtail.core.blocks.RawHTMLBlock(label='HTML'))], blank=True)),
                ('share_description', models.TextField(blank=True, help_text="\n        Default message shown when a page from this site is shared on social media. This message can be\n        changed per page, under the 'promote' tab.\n        ", max_length=150)),
                ('share_image', models.ForeignKey(blank=True, help_text="\n        Default image shown when a page from this site is shared on social media. This image can be\n        changed per page, under the 'promote' tab.\n        ", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
