# Generated by Django 2.2.2 on 2019-07-01 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, help_text='\n        The URL of your organisation\'s Facebook page. E.g.\n        "https://www.facebook.com/organisation_name_or_id"\n        ')),
                ('twitter_handle', models.CharField(blank=True, help_text='Organisation\'s main Twitter handle. E.g. "@orgname"', max_length=16)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShareMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_share_description', models.TextField(blank=True, help_text="\n        Default message shown when a page from this site is shared on social media. This message\n        can be changed per page, under the 'promote' tab.\n        ", max_length=150)),
                ('default_share_image', models.ForeignKey(blank=True, help_text="\n        Default image shown when a page from this site is shared on social media. This image can be\n        changed per page, under the 'promote' tab.\n        ", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Social share text / image',
            },
        ),
        migrations.CreateModel(
            name='HeaderHTML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(blank=True, verbose_name='HTML')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'HTML - Header',
            },
        ),
        migrations.CreateModel(
            name='FooterHTML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(blank=True, verbose_name='HTML')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'HTML - Footer',
            },
        ),
    ]
