# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StructBlock([('link_to', wagtail.core.blocks.ChoiceBlock(choices=[('page', 'Page'), ('file_url', 'File'), ('custom_url', 'Custom URL')], required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('file_url', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('custom_url', wagtail.core.blocks.URLBlock(required=False)), ('new_window', wagtail.core.blocks.BooleanBlock(label='Open in new window', required=False)), ('link_text', wagtail.core.blocks.CharBlock(default='Read more', help_text='This is the text that will appear in the button'))], form_template='admin/blocks/footer_link_block.html', label='link', max_num=5, template='blocks/footer_link_block.html'))])),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', wagtail.core.fields.RichTextField()),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Your Facebook page URL')),
                ('twitter', models.URLField(blank=True, help_text='Your Twitter page URL')),
                ('instagram', models.URLField(blank=True, help_text='Your Instagram page URL')),
                ('youtube', models.URLField(blank=True, help_text='Your YouTube channel URL')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
